/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_shuffle_aggr_DPDK */

#ifndef _Included_org_apache_spark_shuffle_aggr_DPDK
#define _Included_org_apache_spark_shuffle_aggr_DPDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_shuffle_aggr_DPDK
 * Method:    ipc_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_shuffle_aggr_DPDK_ipc_1init
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_spark_shuffle_aggr_DPDK
 * Method:    ipc_workdir
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_shuffle_aggr_DPDK_ipc_1workdir
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_apache_spark_shuffle_aggr_DPDK
 * Method:    ipc_push
 * Signature: (ILjava/lang/String;[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_shuffle_aggr_DPDK_ipc_1push
  (JNIEnv *, jclass, jint, jstring, jintArray, jintArray, jintArray);

/*
 * Class:     org_apache_spark_shuffle_aggr_DPDK
 * Method:    ipc_wait
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_shuffle_aggr_DPDK_ipc_1wait
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_apache_spark_shuffle_aggr_DPDK
 * Method:    ipc_initshm
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_shuffle_aggr_DPDK_ipc_1initshm
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_apache_spark_shuffle_aggr_DPDK
 * Method:    ipc_initall
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_shuffle_aggr_DPDK_ipc_1initall
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_apache_spark_shuffle_aggr_DPDK
 * Method:    ipc_cleanshm
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_shuffle_aggr_DPDK_ipc_1cleanshm
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_apache_spark_shuffle_aggr_DPDK
 * Method:    ipc_write
 * Signature: (II[II)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_shuffle_aggr_DPDK_ipc_1write
  (JNIEnv *, jclass, jint, jint, jintArray, jint);

/*
 * Class:     org_apache_spark_shuffle_aggr_DPDK
 * Method:    ipc_lengths
 * Signature: (II)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_apache_spark_shuffle_aggr_DPDK_ipc_1lengths
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_apache_spark_shuffle_aggr_DPDK
 * Method:    ipc_read
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_apache_spark_shuffle_aggr_DPDK_ipc_1read
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif